### ISSUE TITLE
with PR edited ?

### ISSUE THREAD

**Issue by nelero** [redchamps/customer-shopping-carts-tab#1]
Hi,
thanks for your proposal.
I've read all the discussion and seems that some code was not ideal like : 
` $this->coreRegistry->registry
`
could you merge/edit your files with what Magento DEV edited ?

thanks

**Comment by rav-redchamps** [comment]
Sure, will do it shortly.

**Comment by rav-redchamps** [comment]
Done ✅ Version 1.0.1 has been added with the updates.

**Comment by nelero** [comment]
Great I will test it ASAP
